name = "erdos"
version = "0.1.0"
defaultTargets = ["Erdos"]

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "master"

[[require]]
name = "formal_conjectures"
path = "FormalConjectures"

# Main Erdos library
[[lean_lib]]
name = "Erdos"
globs = ["Erdos.+"]

# Solutions/proofs folder
[[lean_lib]]
name = "Solutions"
globs = ["solutions.+"]
